services:
  blog-api:
    build:
      context: ./blog-api
      dockerfile: Dockerfile
    container_name: blog-api
    volumes:
      - ./blog-api:/var/www/html
    env_file:
      - ./blog-api/.env
    depends_on:
      - redis
      - db
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - ./blog-api:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - blog-api
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: blog-redis
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: blog-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
